### ISSUE TITLE
Design a Logo for Indulge

### ISSUE THREAD

**Issue by raksha009** [dscigdtuw/Indulge#1]
**Task**

You are supposed to design a logo for Indulge . Look for designs which are already present for currently running restaurant websites .
(Include logo designs of both - text type and icon type)

**Implementation**

Tools used : Adobe photoshop , Adobe illustrator, Canva or any other tool convenient to you.
Create designs and share screenshots in comment section
Once finalized create PR

**Procedure**

Claim this issue: Comment below that you want to work on this issue
Write relevant commit message while making a PR

**Comment by nporia** [comment]
I would like to work on this. Please assign me this work.

**Comment by aastha271100** [comment]
I would like to contribute.

**Comment by khushi3108** [comment]
I would like to contribute

**Comment by raksha009** [comment]
Issue has been assigned. Plz start working on it guys🤩

**Comment by khushi3108** [comment]
**I have made the following logos- text and icon. Please have a look!**
![image](https://user-images.githubusercontent.com/60807052/96915635-1b5a9980-14c4-11eb-9c6b-cc5ac2aac932.png)
![image](https://user-images.githubusercontent.com/60807052/96915501-f0704580-14c3-11eb-8296-09395907dee0.png)
![image](https://user-images.githubusercontent.com/60807052/96915544-fe25cb00-14c3-11eb-83c3-b953f6c39fa4.png)
![image](https://user-images.githubusercontent.com/60807052/96915563-02ea7f00-14c4-11eb-9824-d8e867b53d95.png)
![image](https://user-images.githubusercontent.com/60807052/96915585-07af3300-14c4-11eb-82c4-fa1fd0e5c581.png)
![image](https://user-images.githubusercontent.com/60807052/96915621-14cc2200-14c4-11eb-9394-e012c27cd1cb.png)

**Comment by aastha271100** [comment]
![Screenshot 2020-10-23 100343](https://user-images.githubusercontent.com/68474035/96957068-4f12df00-1517-11eb-8e35-7406f1df843c.png)

**Comment by muskaanv0** [comment]
I have made these logos pls check.

![image](https://user-images.githubusercontent.com/62637855/97052144-1833dc00-159e-11eb-923e-8e5601865d34.png)

![image](https://user-images.githubusercontent.com/62637855/97053111-e459b600-159f-11eb-8b8d-9e7e36da7421.png)

![image](https://user-images.githubusercontent.com/62637855/97054118-d442d600-15a1-11eb-860e-0cc407f238a3.png)

**Comment by raksha009** [comment]
Looks great @khushi3108 @aastha271100 @muskaanv0 :)
@khushi3108 plz download the work from canva in .png format and store all yr work in a folder
@aastha271100 your design looks great too. Along with this design, add separate file of logo and "Indulge" text. and then store yr work in folder.
@muskaanv0 plz add some more designes of only text and only logos.

**PS:** plz make the folder name like **yrname_logo** and then add all yr designs here.
Once done @khushi3108 plz make a pr and start working on next issue. and @aastha271100 and @muskaanv0 plz show finalized designs once here and then we are good to go too.

**Comment by raksha009** [comment]
Guys plz finalize this work by tomorrow so that we can start working on other issues too:) And also, if you finish yr work on a issue and a review is pending, plz comment on other issues and start working on them :)

**Comment by manisha1904** [comment]
I have made some logos, please have a look
![1](https://user-images.githubusercontent.com/68684840/97088584-7bca1200-164f-11eb-9ca6-9b809b19d17e.jpeg)
![2](https://user-images.githubusercontent.com/68684840/97088603-9b613a80-164f-11eb-872f-908b8b80e386.jpeg)

**Comment by raksha009** [comment]
@manisha1904 These logos look cool. Also, in addition of these 2 logos, plz break 1 logo into text and pictorial rep. separately. Hence, making it 4 files in total. Plz make these changes and do post the changes in 1st file here.

**Comment by manisha1904** [comment]
![1](https://user-images.githubusercontent.com/68684840/97111418-a4f8aa00-1704-11eb-89f3-515abcf34b03.jpeg)
![2](https://user-images.githubusercontent.com/68684840/97111450-d6717580-1704-11eb-8742-0ccfa7b6c514.jpeg)
![3](https://user-images.githubusercontent.com/68684840/97111463-ed17cc80-1704-11eb-922e-4d0eb858c25f.jpeg)
![4](https://user-images.githubusercontent.com/68684840/97111467-f012bd00-1704-11eb-966b-64b3421bd84f.jpeg)
![5](https://user-images.githubusercontent.com/68684840/97111471-f43eda80-1704-11eb-836b-32015b98faf5.jpeg)

**Comment by raksha009** [comment]
This looks perfect @manisha1904. Plz store all yr designs in the folder name like yrname_logo and then add all yr designs there.
Once done plz make a pr and start working on next issue.

**Comment by muskaanv0** [comment]
pls check the following
![image](https://user-images.githubusercontent.com/62637855/97163798-2d2f8b80-17a7-11eb-8c5b-60775cfedbc2.png)
![image](https://user-images.githubusercontent.com/62637855/97163841-3caed480-17a7-11eb-8f4b-167f21975f6c.png)
![image](https://user-images.githubusercontent.com/62637855/97163851-42a4b580-17a7-11eb-9a72-e1a48ce89e4c.png)
![image](https://user-images.githubusercontent.com/62637855/97164017-839cca00-17a7-11eb-8715-12715afccf16.png)
![image](https://user-images.githubusercontent.com/62637855/97164063-96af9a00-17a7-11eb-8e73-be7fbff78b14.png)

**Comment by nporia** [comment]
I also made a few. Please give them a look.
![2020-10-26 (3)](https://user-images.githubusercontent.com/20817990/97196948-143ccf80-17d3-11eb-8124-bb498cde914a.png)
![2020-10-26 (4)](https://user-images.githubusercontent.com/20817990/97196949-156dfc80-17d3-11eb-9df2-55e75222a805.png)
![2020-10-26 (5)](https://user-images.githubusercontent.com/20817990/97196951-16069300-17d3-11eb-9734-f12e3e14a3cb.png)

**Comment by raksha009** [comment]
Looks cool @nporia and @muskaanv0. Go for the pr and plz store all yr designs in the folder name like yrname_logo and then add all yr designs there.
Once done, plz start working on the  next issue.
