### ISSUE TITLE
Loading Animation for Landing Page

### ISSUE THREAD

**Issue by raksha009** [dscigdtuw/Indulge#2]
**Task**

You are supposed to design a loading animation for Landing Page . Look for various loading animations online on platforms like Codepen.

**Implementation**
Tools used : CSS, JQuery, JS or any other tool convenient to you.
Create animations and share gifs/videos in comment section
Once finalized create PR

**Procedure**
Claim this issue: Comment below that you want to work on this issue
Write relevant commit message while making a PR

**References**
https://orioniconlibrary.com/

**Comment by khushi3108** [comment]
I would like to work on this!. Do we need to have jquey knowlege prior to this, or can we design using Css also?

**Comment by raksha009** [comment]
> I would like to work on this!. Do we need to have jquey knowlege prior to this, or can we design using Css also?

We can design these by only css too. Try googling "loading animations" or "loading animations via css" or "add loading animation on webpage" or something like this. You would encounter various options for the same.

**Comment by shagun0915** [comment]
> I would like to work on this!. Do we need to have jquey knowlege prior to this, or can we design using Css also?

You can draw ideas from the links shared below. There are some really cool loading animations using just CSS. We would need Jquery/JavaScript to incorporate the animation with the site. But the design itself does not require Jquery.

https://designmodo.com/css3-jquery-loading-animations/

https://codepen.io/search/pens?q=loading+animations&__cf_chl_jschl_tk__=38bb1f12b73eb93c6596ecc994490a73b8b29c0a-1603687095-0-Ae3ATqEr2_wVJQ6APVsVCBTLUS5hULtf4DnaagPbTbW9cs3LDACGz3wvScLpKfnHbdwl3GutApPcXrLi_J9E2F707BlWJfKkpvLGfUKczp6xU4h8c6bA1SAOVAm2P-rhYnSbzqZu7UnvVSDUhCDH1mQcqZh3DORd7AQGJfhWhfuJnfsUWlNWf77xvek-uBlJxK66fKvRMj-QcSSqDoWFE4DnjTxICeiNN_vYxw8dqZlJ6o757KNR-9gXh0fLVFXt7jgxTaIVbbCp-U4xLGWFgAarja4qTVgxsFl1x8aanuopamutiQ3CMTkVLLI2qjTa8IBVAWx-JuVqfxM_w883YRRMD-5TuBt_jmIA_iEVXc5dVLCewnBkqrP2ANRlegJ6vw

**Comment by khushi3108** [comment]
> > I would like to work on this!. Do we need to have jquey knowlege prior to this, or can we design using Css also?
> 
> You can draw ideas from the links shared below. There are some really cool loading animations using just CSS. We would need Jquery/JavaScript to incorporate the animation with the site. But the design itself does not require Jquery.
> 
> https://designmodo.com/css3-jquery-loading-animations/
> 
> https://codepen.io/search/pens?q=loading+animations&__cf_chl_jschl_tk__=38bb1f12b73eb93c6596ecc994490a73b8b29c0a-1603687095-0-Ae3ATqEr2_wVJQ6APVsVCBTLUS5hULtf4DnaagPbTbW9cs3LDACGz3wvScLpKfnHbdwl3GutApPcXrLi_J9E2F707BlWJfKkpvLGfUKczp6xU4h8c6bA1SAOVAm2P-rhYnSbzqZu7UnvVSDUhCDH1mQcqZh3DORd7AQGJfhWhfuJnfsUWlNWf77xvek-uBlJxK66fKvRMj-QcSSqDoWFE4DnjTxICeiNN_vYxw8dqZlJ6o757KNR-9gXh0fLVFXt7jgxTaIVbbCp-U4xLGWFgAarja4qTVgxsFl1x8aanuopamutiQ3CMTkVLLI2qjTa8IBVAWx-JuVqfxM_w883YRRMD-5TuBt_jmIA_iEVXc5dVLCewnBkqrP2ANRlegJ6vw

Thankyou! Would research  and learn along! Mught take time but I will try to give my best!!

**Comment by shagun0915** [comment]
> > > I would like to work on this!. Do we need to have jquey knowlege prior to this, or can we design using Css also?
> > 
> > 
> > You can draw ideas from the links shared below. There are some really cool loading animations using just CSS. We would need Jquery/JavaScript to incorporate the animation with the site. But the design itself does not require Jquery.
> > https://designmodo.com/css3-jquery-loading-animations/
> > https://codepen.io/search/pens?q=loading+animations&__cf_chl_jschl_tk__=38bb1f12b73eb93c6596ecc994490a73b8b29c0a-1603687095-0-Ae3ATqEr2_wVJQ6APVsVCBTLUS5hULtf4DnaagPbTbW9cs3LDACGz3wvScLpKfnHbdwl3GutApPcXrLi_J9E2F707BlWJfKkpvLGfUKczp6xU4h8c6bA1SAOVAm2P-rhYnSbzqZu7UnvVSDUhCDH1mQcqZh3DORd7AQGJfhWhfuJnfsUWlNWf77xvek-uBlJxK66fKvRMj-QcSSqDoWFE4DnjTxICeiNN_vYxw8dqZlJ6o757KNR-9gXh0fLVFXt7jgxTaIVbbCp-U4xLGWFgAarja4qTVgxsFl1x8aanuopamutiQ3CMTkVLLI2qjTa8IBVAWx-JuVqfxM_w883YRRMD-5TuBt_jmIA_iEVXc5dVLCewnBkqrP2ANRlegJ6vw
> 
> Thankyou! Would research and learn along! Mught take time but I will try to give my best!!

Ya sure. Take your time.

**Comment by manisha1904** [comment]
I want to work on this issue

**Comment by manisha1904** [comment]
![Loading-Animations1](https://user-images.githubusercontent.com/68684840/97147910-4711a400-1790-11eb-8867-81ac7263d30a.gif)
![Loading-Animations3](https://user-images.githubusercontent.com/68684840/97147943-5133a280-1790-11eb-984e-b3925440b728.gif)
![Loading-Animations2](https://user-images.githubusercontent.com/68684840/97147951-555fc000-1790-11eb-9197-ae8dffb7f8d3.gif)

**Comment by aastha271100** [comment]
I would like to contribute

**Comment by aastha271100** [comment]
https://drive.google.com/file/d/1lSqo4wuyjs6CoNv60w4fwtWpGlQ9Thsw/view?usp=drivesdk

**Comment by khushi3108** [comment]
![20201027_194158_1](https://user-images.githubusercontent.com/60807052/97314155-6b06df80-188d-11eb-970c-8c489725bdb8.gif)
  css animation for logo .

**Comment by raksha009** [comment]
Looks awesome 👌@aastha271100 and @khushi3108 . 
@aastha271100 Try some more options if possible else go forth and make a pr. Also, plz complete the previous issue. That task is also almost done.
@khushi3108 logo animation looks so cool. Try finding some loading animations too :)

**Comment by khushi3108** [comment]
> Looks awesome 👌@aastha271100 and @khushi3108 .
> @aastha271100 Try some more options if possible else go forth and make a pr. Also, plz complete the previous issue. That task is also almost done.
> @khushi3108 logo animation looks so cool. Try finding some loading animations too :)

![Uploading Edited_20201028_082517_1.gif…]()

**Comment by khushi3108** [comment]
> Looks awesome 👌@aastha271100 and @khushi3108 .
> @aastha271100 Try some more options if possible else go forth and make a pr. Also, plz complete the previous issue. That task is also almost done.
> @khushi3108 logo animation looks so cool. Try finding some loading animations too :)
Here's one:-
![Edited_20201028_082517_1](https://user-images.githubusercontent.com/60807052/97385889-b30f1c00-18f8-11eb-9729-58462985bbab.gif)

**Comment by raksha009** [comment]
@khushi3108 is this a gif or a css animation?

**Comment by khushi3108** [comment]
> @khushi3108 is this a gif or a css animation?

This is a gif of css animation

**Comment by raksha009** [comment]
> This is a gif of css animation

Ohkk, looks cool. Try some more options if possible else go forth and make a pr.

**Comment by manisha1904** [comment]
![Chrome (2)](https://user-images.githubusercontent.com/68684840/97401444-d8ab1e00-1916-11eb-9510-24ea9af0a007.GIF)
![Chrome (1)](https://user-images.githubusercontent.com/68684840/97401458-de086880-1916-11eb-8c5c-b9d008497027.GIF)
![Chrome](https://user-images.githubusercontent.com/68684840/97401470-e1035900-1916-11eb-9395-b6138705b336.GIF)

**Comment by raksha009** [comment]
Looks cool @manisha1904. Try implementing this on yr local machine and then we are good to go.
