### ISSUE TITLE
Contemplate a Tagline for Indulge

### ISSUE THREAD

**Issue by raksha009** [dscigdtuw/Indulge#3]
**Task**

Contemplate a catchy tagline for the website. It should go with theme and the logos previously finalized.

**Procedure**

Claim this issue: Comment below that you want to work on this issue
Write relevant commit message while making a PR
Once finalized create PR

**Comment by khushi3108** [comment]
I would like to contribute!

**Comment by khushi3108** [comment]
I have a few taglines:-
From Farm to Fork
Where food speaks with your plate
Where food inebriates you
Every fork has a story
Your wish our choice

**Comment by aditibindal27** [comment]
I would like to contribute!

**Comment by aastha271100** [comment]
I would like to contribute.

**Comment by aastha271100** [comment]
A taste of home
We saved you a seat!
Rain or shine, it’s time to dine
Your grub hub
An oasis of pleasure

**Comment by manisha1904** [comment]
I want to work on this issue

**Comment by aditibindal27** [comment]
The pleasure of variety on your plate
Better food better mood
The grill on fire
Beyond the boundaries of taste
Life tastes better with Indulge
There’s no place like Indulge
Indulge- the Grub Hub

**Comment by manisha1904** [comment]
WHERE FOOD CELEBRATES LIFE
SERVICE. CARE. TRADITION
SERVING UP GREAT MEMORIES
FEED YOUR DREAMS
FOOD IN YOUR BUDGET

**Comment by raksha009** [comment]
@aditibindal27 @khushi3108 @aastha271100 @manisha1904 plz create a pr and add your taglines in **tagline.md** file in the repo.
